Fixed Specific Clients and Fixed :Stop()
Steadyon/TweenServiceV2 pull request #4
Opened 2021-10-13 00:24 UTC by jeffreydeen

Added SpecificClient when calling :FireClient(), and changed tween:Stop() to tween:Cancel(). ( left the function as tweenMaster:Stop for backwards compatibility, but changed the actual tween calling :Stop() to :Cancel() )

2022-08-25 11:40 UTC, marceaupatu123 commented
@Steadyon

2022-11-05 08:21 UTC, EgizianoEG approved these changes

2022-11-05 08:25 UTC, EgizianoEG requested changes
It should be fixed...
@Steadyon

2025-06-07 17:02 UTC, Steadyon commented
Can you resolve the conflicts please ?

2025-09-29 22:41 UTC, closed without merging

2025-09-29 22:41 UTC, Steadyon commented
Closing this now. It's possible I caused the conflicts at the time by merging some other changes, but if you still want to contribute something please submit another PR. Thanks for submitting this.